global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'finance-tracker'

scrape_configs:
  - job_name: 'finance-tracker-app'
    static_configs:
      - targets: ['app:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
